"""Core primitives for the FNP-QNN research prototype."""

from .cerebrum_adapter import CerebrumAdapter, CerebrumFeatureBundle, CrossModalEvent
from .cloud_rag_bridge import (
    RAG_KEY_ENV,
    admission_to_runtime_payload,
    build_admission,
    cloud_kit_status,
    decrypt_admission,
    e2b_ingest_plan,
    e2b_smoke,
    encrypt_admission,
    envelope_to_runtime_payload,
    generate_rag_key,
    load_env_file,
)
from .cerebrum_runtime_bridge import CerebrumMemoryEvent, CerebrumRuntimeBridge, CerebrumRuntimeState, CrossModalPair
from .cpai_mesh import CPAIMeshState, cpai_mesh_profile
from .lvfm_runtime_graph import (
    LVFMRuntimeGraph,
    LVFMDecision,
    LVFMDirection,
    RegisterBit,
    RegisterKey,
)
from .lvfm_gate_ledger import LVFMGateLedger, LVFMGateRecord
from .lvfm_registry_anchor import DEFAULT_LOCK_THRESHOLD, RegistryAnchoringResult, compute_lock_state, publish_gate_state
from .life_science_port import LifeScienceObservationPort
from .phi_framework import PhiFramework, QuantumState
from .qlc_runtime_normalizer import normalize_qlc_runtime_payload, qlc_runtime_summary
from .qnn_nucleus import QNNBenchmarkResult, QNNCandidate, QNNNucleus
from .ffed_plugin_bridge import FfeDPluginBridge, MVP5_PLUGIN_IDS, NEXT5_PLUGIN_IDS
from .neurobit_gate_tunnel import (
    NeuroBitProfile,
    run_neurobit_gates,
    run_neurobit_tunnel_demo,
)
from .experiment_seed import ExperimentSeedManager
from .quantum_feature_transforms import (
    complex_wavefunction_to_amplitude_phase_features,
    structure_vector_to_phi_scaled_state,
)
from .neutrosophic_quantum_primitives import (
    CoherentNeutroState,
    DecoherentNeutroState,
    FractalCarrierContext,
    NeutrobitState,
    fractal_carrier_profile,
    neutrobit_features_from_vector,
    neutrosophic_gate_algebra,
    neutrosophic_measurement,
    normalize_fractal_dimension,
    observer_effect_profile,
    partial_entanglement_profile,
    punctured_surface_state,
    punctured_wave_state,
)
from .penrose_hameroff_math import (
    microtubule_signal_profile,
    objective_reduction_profile,
    orchestration_profile,
    penrose_hameroff_runtime_profile,
    spin_network_admissibility_profile,
    twistor_nonlocality_profile,
)
from .hydra_em_gpcn_math import (
    anesthesia_sweep_profile,
    gpcn_set_phi_profile,
    hydra_em_gpcn_orch_profile,
    microtubule_proxy_phi_profile,
    quasicrystal_gpcn_projection_profile,
)
from .axiomatic_chamber import (
    AxiomaticChamberContext,
    ChamberBounds,
    SourceRole,
    admissibility_profile,
    dmin_dmax_chamber_bounds,
)
from .gravity_null_test import (
    GravityNullTestConfig,
    bell_state_reference_profile,
    bell_vs_gravity_chamber_taxonomy,
    e2b_datadog_review_profile,
    gravity_null_test_status,
    graviton_constraint_profile,
    run_gravity_null_test,
    sequence_event_spec,
)
from .multiverse_experiments import (
    MULTIVERSE_EXPERIMENT_IDS,
    MultiverseExperimentConfig,
    multiverse_experiments_status,
    run_all_multiverse_experiments,
    run_multiverse_experiment,
)
from .time_physics_experiments import (
    TIME_PHYSICS_EXPERIMENT_IDS,
    TimePhysicsExperimentConfig,
    run_all_time_physics_experiments,
    run_time_physics_experiment,
    time_physics_experiments_status,
)
from .neutro_algebra import (
    neutro_axiom_profile,
    neutro_function_profile,
    neutro_operation_table_profile,
    neutroalgebra_runtime_profile,
    neutroalgebra_structure_profile,
    tri_section_space_profile,
)
from .neutro_structure import (
    neutro_attribute_profile,
    neutro_relation_profile,
    neutrostructure_profile,
    runtime_neutrostructure_profile,
)
from .nidus_idearum_math import (
    partial_membership_mean,
    source_weighted_triplet_fusion,
    triplet_quality_profile,
)
from .plithogenic_logic import (
    plithogenic_attribute_profile,
    plithogenic_contradiction_degree,
    plithogenic_neutrosophic_conjunction,
    plithogenic_runtime_fusion_profile,
    plithogenic_weighted_cumulative_truth,
)
from .plithogenic_probability_statistics import (
    plugin_stabilization_profile,
    plithogenic_multi_to_uni_decision,
    plithogenic_probability_family_profile,
    plithogenic_topology_load_profile,
    plithogenic_topology_wiring_profile,
    plithogenic_variate_sample_profile,
    refined_plithogenic_statistical_components,
)
from .revolutionary_topologies import (
    deformation_invariant_signature,
    nonstandard_neighborhood_profile,
    refined_topology_components,
    revolutionary_topology_runtime_profile,
    topological_axiom_profile,
)
from .runtime_state_store import RuntimeStateStore

__version__ = "1.2.0-research"
__author__ = "SeCuReDmE Innovation Lab"

__all__ = [
    "PhiFramework",
    "QuantumState",
    "CrossModalEvent",
    "CerebrumFeatureBundle",
    "CerebrumAdapter",
    "RAG_KEY_ENV",
    "admission_to_runtime_payload",
    "build_admission",
    "cloud_kit_status",
    "decrypt_admission",
    "e2b_ingest_plan",
    "e2b_smoke",
    "encrypt_admission",
    "envelope_to_runtime_payload",
    "generate_rag_key",
    "load_env_file",
    "CerebrumMemoryEvent",
    "CrossModalPair",
    "CerebrumRuntimeState",
    "CerebrumRuntimeBridge",
    "CPAIMeshState",
    "cpai_mesh_profile",
    "RegisterBit",
    "RegisterKey",
    "LVFMDirection",
    "LVFMDecision",
    "LVFMRuntimeGraph",
    "LVFMGateLedger",
    "LVFMGateRecord",
    "DEFAULT_LOCK_THRESHOLD",
    "RegistryAnchoringResult",
    "compute_lock_state",
    "publish_gate_state",
    "LifeScienceObservationPort",
    "normalize_qlc_runtime_payload",
    "qlc_runtime_summary",
    "QNNCandidate",
    "QNNBenchmarkResult",
    "QNNNucleus",
    "FfeDPluginBridge",
    "MVP5_PLUGIN_IDS",
    "NEXT5_PLUGIN_IDS",
    "NeuroBitProfile",
    "run_neurobit_gates",
    "run_neurobit_tunnel_demo",
    "ExperimentSeedManager",
    "complex_wavefunction_to_amplitude_phase_features",
    "structure_vector_to_phi_scaled_state",
    "CoherentNeutroState",
    "DecoherentNeutroState",
    "FractalCarrierContext",
    "NeutrobitState",
    "fractal_carrier_profile",
    "neutrobit_features_from_vector",
    "neutrosophic_gate_algebra",
    "neutrosophic_measurement",
    "normalize_fractal_dimension",
    "observer_effect_profile",
    "partial_entanglement_profile",
    "punctured_surface_state",
    "punctured_wave_state",
    "microtubule_signal_profile",
    "objective_reduction_profile",
    "orchestration_profile",
    "penrose_hameroff_runtime_profile",
    "spin_network_admissibility_profile",
    "twistor_nonlocality_profile",
    "anesthesia_sweep_profile",
    "gpcn_set_phi_profile",
    "hydra_em_gpcn_orch_profile",
    "microtubule_proxy_phi_profile",
    "quasicrystal_gpcn_projection_profile",
    "AxiomaticChamberContext",
    "ChamberBounds",
    "SourceRole",
    "admissibility_profile",
    "dmin_dmax_chamber_bounds",
    "GravityNullTestConfig",
    "bell_state_reference_profile",
    "bell_vs_gravity_chamber_taxonomy",
    "e2b_datadog_review_profile",
    "gravity_null_test_status",
    "graviton_constraint_profile",
    "run_gravity_null_test",
    "sequence_event_spec",
    "MULTIVERSE_EXPERIMENT_IDS",
    "MultiverseExperimentConfig",
    "multiverse_experiments_status",
    "run_all_multiverse_experiments",
    "run_multiverse_experiment",
    "TIME_PHYSICS_EXPERIMENT_IDS",
    "TimePhysicsExperimentConfig",
    "run_all_time_physics_experiments",
    "run_time_physics_experiment",
    "time_physics_experiments_status",
    "neutro_axiom_profile",
    "neutro_function_profile",
    "neutro_operation_table_profile",
    "neutroalgebra_runtime_profile",
    "neutroalgebra_structure_profile",
    "tri_section_space_profile",
    "neutro_attribute_profile",
    "neutro_relation_profile",
    "neutrostructure_profile",
    "runtime_neutrostructure_profile",
    "partial_membership_mean",
    "source_weighted_triplet_fusion",
    "triplet_quality_profile",
    "plithogenic_attribute_profile",
    "plithogenic_contradiction_degree",
    "plithogenic_neutrosophic_conjunction",
    "plithogenic_runtime_fusion_profile",
    "plithogenic_weighted_cumulative_truth",
    "plugin_stabilization_profile",
    "plithogenic_multi_to_uni_decision",
    "plithogenic_probability_family_profile",
    "plithogenic_topology_load_profile",
    "plithogenic_topology_wiring_profile",
    "plithogenic_variate_sample_profile",
    "refined_plithogenic_statistical_components",
    "deformation_invariant_signature",
    "nonstandard_neighborhood_profile",
    "refined_topology_components",
    "revolutionary_topology_runtime_profile",
    "topological_axiom_profile",
    "RuntimeStateStore",
]
